name: Deploy

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: print variable
        run: echo "${{ secrets.TOKEN_SECRETS }}"

        # Nos sitúa dentro del directorio
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: '18'
# Busca la carpeta y haga este paso (por eso usamos el pipe | )
      - name: install dependecies
        run: | 
          cd angularProject
          npm install
# Cuando tengamos test y querramos que se valide si falla no se ejecuta el resto
      # - name: Run test
      #   run: npm run test

# Esto es un artifact para github pages
      - name: Build page
        run: npm run build
        working-directory: angularProject

# Proviene del marketplace (upload-github-pages-artifact)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: angularProject/public


  deploy:
  # Forzamos a que se ejecute (es util cuando el step nos envía un mensaje  )
    if: ${{ always() }} 
    runs-on: ubuntu-latest
    needs: first_job

    environment:
    # Esta action requiere que esto se exponga a nivel job
      name: github-pages
      url: ${{ steps.deployment-pages.outputs.page_url }} 

    steps:
      - name: Deploy
        id: deployment-pages
# Proviene del marketplace (upload-github-pages-artifact)
# Ver como funciona este paquete
# Se obtine la url a traves de pages a traves de su id
        uses: actions/deploy-pages@v4